version: '3.7' 

services: 
  backend:
    build: 
      context: portfolio-backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      MONGO_USER: root
      MONGO_PASS: pass
      MONGO_SERVICE_NAME: mongo
      MONGO_PORT: 27017
      MONGO_COLLECTION: books
      MONGO_AUTHSOURCE: admin
      LOGGING_URL: logstash
    ports:
     - 5000:5000
    networks:
     - app
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITSCRIPTS_DIR: /docker-entrypoint-initdb.d
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
    - 27017:27017
    volumes:
    - ./scripts:/docker-entrypoint-initdb.d
    - mongodata:/data/db
    networks:
    - app

  nginx:
    # image: nginx
    build: 
      context: react-front-portfolio
      dockerfile: Dockerfile
    container_name: nginx
    environment:
      ADDRESS: asdasd
      BACKEND_SERVICE: backend
      NGINX_PORT: 80
    ports:
     - 8082:80
    networks:
     - app
    command: /bin/sh -c "export BACKEND_SERVICE && export ADDRESS && envsubst '$${ADDRESS} $${BACKEND_SERVICE}' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

volumes:
  mongodata:
    name: mongodata
networks:
  app:
    name: app
    external: true
