apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  version: "1.20"
  name: MaciejBekasEKS
  region: eu-west-2

managedNodeGroups:
  - name: master
    instanceType: t2.medium
    minSize: 2
    maxSize: 2
    volumeSize: 10
    volumeType: gp2
    labels: {role: master}
    tags:
      nodegroup-role: master
      created_by: MaciejBekas
      bootcamp: Poland
